// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cffiattcpldtkaeiwtfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmZmlhdHRjcGxkdGthZWl3dGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NzAxNzAsImV4cCI6MjA1NjI0NjE3MH0.1ed8Ch7JpYetSRG_-336CZUP05DVNRGWL84yCoiE9b0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);